name: Python CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '/skip-ci') && !contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies (production)
        run: |
          pip install -r requirements.txt

      - name: Install dev dependencies (for testing)
        run: |
          pip install -r dev-requirements.txt

      - name: Run tests
        run: |
          pytest test_initializer.py
